[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "notion"
version = "2.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["REST", "API", "Notion", "Notes"]
icon = "icon.png" 
repository = "https://github.com/ballerina-platform/module-ballerinax-notion"
export = ["notion"]

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
